[package]
name = "redback"
description = "The build tool used by eucalyptus game engine"

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
