[workspace]
resolver = "3"
members = ["dropbear-engine", "eucalyptus", "redback"]

[profile.dev]
opt-level = 0
debug = true
codegen-units = 16
incremental = true
lto = false

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
debug = false
incremental = false
