[package]
name = "gleek"
edition.workspace = true
description = "A way to generate Gleam stubs for your rust code (assuming its compiled to JavaScript)"
version = "0.0.1"
license = "MIT"
repository.workspace = true
readme = "README.md"

[dependencies]
