[package]
name = "dropbear-engine"
description = "A game engine made by 4tkbytes. Thats really it..."

version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytemuck.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
egui.workspace = true
egui_extras.workspace = true
env_logger.workspace = true
futures.workspace = true
gilrs.workspace = true
hecs.workspace = true
log.workspace = true
mint.workspace = true
nalgebra.workspace = true
num-traits.workspace = true
pollster.workspace = true
russimp.workspace = true
spin_sleep.workspace = true
tokio.workspace = true
wgpu.workspace = true
winit.workspace = true

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]
