[package]
name = "dropbear-engine"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "A game engine made by 4tkbytes. Thats really it..."
repository = "https://github.com/4tkbytes/dropbear-engine"
readme = "../README.md"

[dependencies]
anyhow = "1.0.98"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11"
log = "0.4"
wgpu = "25"
pollster = "0.4"

