[package]
name = "dropbear-engine"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "A game engine made by 4tkbytes. Thats really it..."
repository = "https://github.com/4tkbytes/dropbear-engine"
readme = "../README.md"

[dependencies]
anyhow = "1.0.98"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11"
log = "0.4"
wgpu = "25"
pollster = "0.4"
# Never block on with async, use tokio instead...
# Note to self: use pollster only for state blocking, any resource loading should not be blocked. 
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
bytemuck = { version = "1.23", features = ["derive"] }
spin_sleep = "1.3"
nalgebra = "0.33"
num-traits = "0.2"
russimp = { version = "3.2", features = ["prebuilt"] }
egui = "0.32"
egui-winit = "0.32"
egui-wgpu = { version = "0.32", features = ["winit"] }
egui_extras = "0.32"
gilrs = "0.11"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"