[package]
name = "dropbear-shader"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
wesl = { workspace = true }

[build-dependencies]
wesl = { workspace = true, features = ["package"] }
