[package]
name = "eucalyptus"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
dropbear-engine = { path = "../dropbear-engine" }
rfd = "0.15.4"
git2 = "0.20.2"
anyhow = "1.0.98"
ron = "0.10.1"
chrono = "0.4.41"
egui-toast = "0.17.0"
egui_dock = { git = "https://github.com/Adanos020/egui_dock" }

[dependencies.rhai]
version = "*"
features = ["std"]

[profile.dev]
opt-level = 0
debug = true
codegen-units = 16
incremental = true
lto = false
