name: Build Executables

on:
  push:
    branches: 
    - '**'
  pull_request: {}

jobs:
  build:
    if: contains(github.event.head_commit.message, 'jarvis, run github actions')
    name: Build for ${{ matrix.os_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_name: windows-x64
            target: x86_64-pc-windows-msvc
            ext: .exe
          - os: ubuntu-latest
            os_name: linux-x64
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            os_name: macos-arm64
            target: aarch64-apple-darwin
            ext: ""

    steps:
      - uses: actions/checkout@v4

      - name: Install libudev-dev (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Install assimp-utils (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y assimp-utils

      - name: Install assimp (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install assimp

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build eucalyptus
        run: cargo build --release --package eucalyptus --target ${{ matrix.target }}

      - name: Download README.md from gist (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          curl -L -o README.md https://gist.github.com/4tkbytes/05576d43fa12e7e2331dd7eb4e606bca/raw/README.md

      - name: Prepare artifact
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/eucalyptus${{ matrix.ext }} dist/
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            cp README.md dist/
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os_name }}
          path: dist/
