name: Gen Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g typedoc typescript
          # Install any project dependencies if package.json exists
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Generate documentation
        run: |
          npx typedoc eucalyptus/src/dropbear.ts \
            --out docs \
            --name "Dropbear Engine Documentation" \
            --theme default \
            --readme README.md \
            --includeVersion \
            --excludePrivate \
            --excludeProtected

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4